### ISSUE TITLE
Frame Work for API Use Established

### ISSUE THREAD

**Issue by NathanSteinway** [NathanSteinway/super-octo-broccoli#3]
Lay groundwork for API use in primary document.

Develop a game-plan for API Implementation and share it w/ team.
* What APIs are we using?
* How will we use them?
* Which APIs will our buttons and form fields interact with?
* Which APIs will our item images and specifications be pulled from?

**Comment by sweattk** [comment]
### What APIs are we using? ### 

**We are using googles & neweggs, APIs.**

**Comment by sweattk** [comment]
### Which APIs will our item images and specifications be pulled from? ###

**GOOGLES**

**Comment by sweattk** [comment]
### Which APIs will our buttons and form fields interact with?

**GOOGLES and NEWEGG**

**Comment by sweattk** [comment]
> ### Which APIs will our buttons and form fields interact with?
> **GOOGLES and NEWEGG**

We will not be using NEWEGGS API. We will be using AMAZONS

**Comment by NathanSteinway** [comment]
@sweattk So we aren't using Newegg's API? We'll be using Amazon's instead?
